Add the login section in the GUI to login
takashiro/asmodee-werewolf-react pull request #8
Opened 2019-05-23 00:33 UTC by Celthi

@takashiro 
This code is to show how the front GUI to interact with the back end login API in: https://github.com/takashiro/asmodee-werewolf-server/pull/3

This code is not the finalize yet, since I have add any CSS style and the logic to handle after the user login.

2019-05-23 02:32 UTC, Celthi commented
continuous-integration/travis-ci/pr

2019-06-02 08:00 UTC, takashiro requested changes

2019-06-02 08:00 UTC, takashiro commented on src/gui/User/User.js
> +	onUpdatename(name) {
Camel-case naming?

2019-06-02 08:00 UTC, takashiro commented on src/gui/User/Login.scss
> +	visibility: visible;
Why not display: none? Do we need to reserve some space for the invisible element?

2019-06-02 08:00 UTC, takashiro commented on src/gui/User/login.js
> +				<form onSubmit={this.login}>
This part needs to be styled.

2019-06-02 08:00 UTC, takashiro commented on src/index.js
> +import User from './gui/User/User';
The path /User/User here looks not hierarchical.

2019-06-02 08:00 UTC, takashiro commented on dist/index.html
> +		<div id="user"></div>
It seems unnecessary to add a new root node. The implementation of login page is straightforward but not ideal.

2019-06-02 08:00 UTC, takashiro commented on src/gui/User/login.js
> +					<input type="submit"></input>
button tag is easier to customize styles.

2019-06-02 08:10 UTC, takashiro commented
nginx is able to customize the root index file, as the nginx.conf you created contains 
```
index    index.html index.htm index.php;
```

2019-06-13 01:51 UTC, Celthi commented
@takashiro 
Your comments are very high value. I'll change them when I have time.
Currently, the code is to demo the idea of the user login in the `asmodee-server`.
If we agree to use this approach, then I'll revise the code.

2019-07-21 23:11 UTC, Celthi commented on src/gui/User/User.js
> +	onUpdatename(name) {
Updated.

2019-07-21 23:11 UTC, Celthi commented on src/gui/User/Login.scss
> +	visibility: visible;
Changed.

2019-07-21 23:11 UTC, Celthi commented on src/gui/User/login.js
> +				<form onSubmit={this.login}>
Sytled.

2019-07-21 23:11 UTC, Celthi commented on src/index.js
> +import User from './gui/User/User';
Changed.

2019-07-21 23:12 UTC, Celthi commented on src/gui/User/login.js
> +					<input type="submit"></input>
Changed.

2019-07-21 23:12 UTC, Celthi commented on dist/index.html
> +		<div id="user"></div>
Yeah.

2020-08-26 13:11 UTC, Celthi commented
Close this immature PR.

2020-08-26 13:11 UTC, closed without merging